FROM node:lts-hydrogen

WORKDIR /apps

COPY . .

RUN npm install --production

ENV MONGO_STRING=mongodb+srv://gilangmgm98:G1lang1998@gilangmgm98.m3hqfwj.mongodb.net/test
ENV NODE_ENV=production
ENV PORT=4001


EXPOSE 4001

CMD ["node", "app.js"]